"""Plain-language summaries of a coverage, generated by the LLM and stored.

A sub-resource of coverages, scoped through own_coverage exactly like
financials. Nothing here catches an LLM failure: errors.py maps each insight
error to a status code, the same way it does for EDGAR.
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import func, select
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

import insight
from config import get_settings
from db import get_db
from financials import own_coverage
from indicators import compute_indicators
from models import Coverage, CoverageFinancial, CoverageSummary
from schemas import CoverageSummaryRead
from security import AuthenticatedUser, require_auth

router = APIRouter(prefix="/api/coverages/{coverage_id}/summary", tags=["summaries"])


def _company_label(coverage: Coverage) -> str:
    # The ticker or CIK, never the user's own title or notes: only public data
    # leaves the service.
    return coverage.ticker or f"CIK {coverage.cik}"


def _stored_summary(db: Session, coverage_id: int) -> CoverageSummary | None:
    return db.scalars(
        select(CoverageSummary).where(CoverageSummary.coverage_id == coverage_id)
    ).one_or_none()


@router.post("", response_model=CoverageSummaryRead)
def generate_summary(
    coverage_id: int,
    user: AuthenticatedUser = Depends(require_auth),
    db: Session = Depends(get_db),
) -> CoverageSummary:
    """Compute indicators from the stored figures, have the LLM word them, store it.

    POST, like collecting financials: it calls another system and writes a row.
    Repeating it replaces the previous summary.
    """
    coverage = own_coverage(db, coverage_id, user)
    rows = db.scalars(
        select(CoverageFinancial).where(CoverageFinancial.coverage_id == coverage.id)
    ).all()

    result = compute_indicators(coverage.cik, rows)
    if result is None:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="No financial figures have been collected for this coverage yet. "
            "Collect them first, then generate the summary.",
        )

    sent = {"fiscal_year_end": result.period_end.isoformat(), **result.values}
    coverage_id, company = coverage.id, _company_label(coverage)
    # End the read-only transaction before the slow LLM call, so the connection
    # is not held idle in transaction for up to ~40 s. Nothing was written.
    db.rollback()
    text = insight.request_summary(company, sent)

    sources = [
        {
            "concept": s.concept,
            "accn": s.accn,
            "form": s.form,
            "filed": s.filed.isoformat(),
            "url": s.url,
        }
        for s in result.sources
    ]
    row = {
        "coverage_id": coverage_id,
        "period_end": result.period_end,
        "indicators": sent,
        "summary": text,
        "model": get_settings().llm_model,
        "sources": sources,
    }
    # One statement, so two generations at once cannot trip the unique key.
    statement = insert(CoverageSummary).values(row)
    db.execute(
        statement.on_conflict_do_update(
            index_elements=[CoverageSummary.coverage_id],
            set_={**{k: statement.excluded[k] for k in row if k != "coverage_id"},
                  "generated_at": func.now()},
        )
    )
    db.commit()

    return _stored_summary(db, coverage_id)


@router.get("", response_model=CoverageSummaryRead)
def read_summary(
    coverage_id: int,
    user: AuthenticatedUser = Depends(require_auth),
    db: Session = Depends(get_db),
) -> CoverageSummary:
    """The stored summary. Reading never calls the LLM, so it spends no quota."""
    coverage = own_coverage(db, coverage_id, user)
    summary = _stored_summary(db, coverage.id)
    if summary is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No summary has been generated for this coverage yet",
        )
    return summary
