import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount, type DOMWrapper, type VueWrapper } from '@vue/test-utils'

import { ApiError } from '@/api/client'
import {
  collectFinancials,
  generateSummary,
  getSummary,
  type CollectionReport,
  type CoverageSummary as Summary,
} from '@/api/summaries'
import CoverageSummary from '@/views/CoverageSummary.vue'

vi.mock('@/api/summaries')

const SEC_URL = 'https://www.sec.gov/Archives/edgar/data/320193/000032019325000079/'

const APPLE_SUMMARY: Summary = {
  period_end: '2025-09-27',
  indicators: {
    fiscal_year_end: '2025-09-27',
    revenue_growth_pct: 6.4,
    net_margin_pct: 26.9,
    equity_ratio_pct: null,
  },
  summary: 'Revenue grew 6.4% on the prior year.\nNet margin was 26.9%.',
  model: 'gpt-4o-mini',
  sources: [{ concept: 'Revenues', accn: '0000320193-25-000079', form: '10-K', filed: '2025-10-31', url: SEC_URL }],
  generated_at: '2026-10-06T07:00:00Z',
}

const NO_SUMMARY = new ApiError(404, 'No summary has been generated for this coverage yet')

describe('CoverageSummary', () => {
  let wrapper: VueWrapper | undefined

  beforeEach(() => {
    vi.mocked(getSummary).mockReset()
    vi.mocked(generateSummary).mockReset()
    vi.mocked(collectFinancials).mockReset()
  })

  afterEach(() => {
    wrapper?.unmount()
  })

  function mountSummary(): VueWrapper {
    wrapper = mount(CoverageSummary, { props: { coverageId: '7' } })
    return wrapper
  }

  function button(page: VueWrapper, label: string): DOMWrapper<HTMLButtonElement> {
    const found = page.findAll('button').find((candidate) => candidate.text() === label)
    if (found === undefined) throw new Error(`No button labelled "${label}"`)
    return found
  }

  it('shows a loading state until the summary arrives', () => {
    vi.mocked(getSummary).mockReturnValue(new Promise(() => {}))
    const page = mountSummary()

    expect(page.find('[role="status"]').text()).toBe('Loading summary…')
    expect(getSummary).toHaveBeenCalledWith('7')
  })

  it('treats a missing summary as empty, not as a failure', async () => {
    vi.mocked(getSummary).mockRejectedValue(NO_SUMMARY)
    const page = mountSummary()
    await flushPromises()

    expect(page.text()).toContain('No summary has been generated for this coverage yet.')
    expect(page.find('[role="alert"]').exists()).toBe(false)
    expect(button(page, 'Generate summary').exists()).toBe(true)
  })

  it('offers a retry when the summary could not be loaded', async () => {
    vi.mocked(getSummary)
      .mockRejectedValueOnce(new ApiError(0, 'Could not reach the server.'))
      .mockResolvedValueOnce(APPLE_SUMMARY)
    const page = mountSummary()
    await flushPromises()

    expect(page.find('[role="alert"]').text()).toContain('Could not load the summary.')

    await button(page, 'Retry').trigger('click')
    await flushPromises()

    expect(getSummary).toHaveBeenCalledTimes(2)
    expect(page.find('.summary-text').text()).toContain('Revenue grew 6.4%')
  })

  it('shows the summary with the figures it was written from', async () => {
    vi.mocked(getSummary).mockResolvedValue({
      ...APPLE_SUMMARY,
      indicators: { ...APPLE_SUMMARY.indicators, debt_ratio_pct: 40 },
    })
    const page = mountSummary()
    await flushPromises()

    expect(page.find('.summary-text').text()).toBe(APPLE_SUMMARY.summary)
    expect(page.text()).toContain('Generated by gpt-4o-mini')
    const figures = page.find('dl').text()
    expect(figures).toContain('Net margin (%)')
    expect(figures).toContain('26.9')
    expect(figures).toContain('Not available')
    // A key this page has no label for still shows, under its own name.
    expect(figures).toContain('debt_ratio_pct')
    expect(button(page, 'Regenerate summary').exists()).toBe(true)
  })

  it('links each source to its EDGAR filing in a new tab', async () => {
    vi.mocked(getSummary).mockResolvedValue(APPLE_SUMMARY)
    const page = mountSummary()
    await flushPromises()

    const link = page.find('li a')
    expect(link.text()).toBe('10-K filed 2025-10-31')
    expect(link.attributes('href')).toBe(SEC_URL)
    expect(link.attributes('target')).toBe('_blank')
    expect(link.attributes('rel')).toBe('noopener noreferrer')
  })

  it('does not turn a source URL outside EDGAR into a link', async () => {
    const hostile = { ...APPLE_SUMMARY.sources[0]!, url: 'javascript:alert(1)' }
    vi.mocked(getSummary).mockResolvedValue({ ...APPLE_SUMMARY, sources: [hostile] })
    const page = mountSummary()
    await flushPromises()

    expect(page.find('li a').exists()).toBe(false)
    expect(page.find('li').text()).toContain('10-K filed 2025-10-31')
  })

  it('renders a hostile summary as text, never as markup', async () => {
    const hostile = '<img src=x onerror="document.title = \'pwned\'">'
    vi.mocked(getSummary).mockResolvedValue({ ...APPLE_SUMMARY, summary: hostile })
    const page = mountSummary()
    await flushPromises()

    expect(page.find('img').exists()).toBe(false)
    expect(page.find('.summary-text').text()).toBe(hostile)
  })

  it('generates a summary and shows the stored result', async () => {
    vi.mocked(getSummary).mockRejectedValueOnce(NO_SUMMARY).mockResolvedValueOnce(APPLE_SUMMARY)
    vi.mocked(generateSummary).mockResolvedValue(APPLE_SUMMARY)
    const page = mountSummary()
    await flushPromises()

    await button(page, 'Generate summary').trigger('click')
    await flushPromises()

    expect(generateSummary).toHaveBeenCalledWith('7')
    expect(getSummary).toHaveBeenCalledTimes(2)
    expect(page.find('.summary-text').text()).toContain('Revenue grew 6.4%')
  })

  it('locks both actions while a summary is being generated', async () => {
    vi.mocked(getSummary).mockRejectedValue(NO_SUMMARY)
    vi.mocked(generateSummary).mockReturnValue(new Promise(() => {}))
    const page = mountSummary()
    await flushPromises()

    await button(page, 'Generate summary').trigger('click')

    expect(button(page, 'Generating…').attributes('disabled')).toBeDefined()
    expect(button(page, 'Collect financials').attributes('disabled')).toBeDefined()
  })

  it('shows the server message when the figures have not been collected', async () => {
    const message = 'No financial figures have been collected for this coverage yet.'
    vi.mocked(getSummary).mockRejectedValue(NO_SUMMARY)
    vi.mocked(generateSummary).mockRejectedValue(new ApiError(409, message))
    const page = mountSummary()
    await flushPromises()

    await button(page, 'Generate summary').trigger('click')
    await flushPromises()

    expect(page.find('[role="alert"]').text()).toBe(message)
    expect(button(page, 'Generate summary').attributes('disabled')).toBeUndefined()
  })

  it('keeps an unexpected server failure out of the page', async () => {
    vi.mocked(getSummary).mockResolvedValue(APPLE_SUMMARY)
    vi.mocked(generateSummary).mockRejectedValue(new ApiError(500, 'Internal Server Error'))
    const page = mountSummary()
    await flushPromises()

    await button(page, 'Regenerate summary').trigger('click')
    await flushPromises()

    expect(page.find('[role="alert"]').text()).toBe('Could not generate the summary. Please try again.')
    // The earlier summary stays: a failed generation replaces nothing.
    expect(page.find('.summary-text').text()).toContain('Revenue grew 6.4%')
  })

  it('collects the financial figures and reports how many', async () => {
    vi.mocked(getSummary).mockRejectedValue(NO_SUMMARY)
    // Held open so the in-progress state can be checked before it finishes.
    let finish: (report: CollectionReport) => void = () => {}
    vi.mocked(collectFinancials).mockReturnValue(new Promise((resolve) => (finish = resolve)))
    const page = mountSummary()
    await flushPromises()

    await button(page, 'Collect financials').trigger('click')
    expect(button(page, 'Collecting…').attributes('disabled')).toBeDefined()
    expect(button(page, 'Generate summary').attributes('disabled')).toBeDefined()

    finish({ coverage_id: 7, collected: 12, concepts: ['Revenues'] })
    await flushPromises()

    expect(collectFinancials).toHaveBeenCalledWith('7')
    expect(page.find('[role="status"]').text()).toBe('Collected 12 figures.')
  })

  it('shows the server message when the data provider is unreachable', async () => {
    const message = 'The external data provider is temporarily unreachable. Try again shortly.'
    vi.mocked(getSummary).mockRejectedValue(NO_SUMMARY)
    vi.mocked(collectFinancials).mockRejectedValue(new ApiError(503, message))
    const page = mountSummary()
    await flushPromises()

    await button(page, 'Collect financials').trigger('click')
    await flushPromises()

    expect(page.find('[role="alert"]').text()).toBe(message)
    expect(page.find('[role="status"]').exists()).toBe(false)
  })
})
