<script setup lang="ts">
import { ref } from 'vue'

import { ApiError, NETWORK_ERROR_STATUS } from '@/api/client'
import { collectFinancials, generateSummary, getSummary } from '@/api/summaries'
import { useRequest } from '@/composables/useRequest'

const props = defineProps<{ coverageId: string }>()

const NOT_FOUND = 404
const CONFLICT = 409
const BAD_GATEWAY = 502
const SERVICE_UNAVAILABLE = 503
// The server words these for the user (collect first, try again shortly); other failures it does not.
const SHOWN_AS_IS = new Set([NETWORK_ERROR_STATUS, CONFLICT, BAD_GATEWAY, SERVICE_UNAVAILABLE])

// Only EDGAR links are rendered: Vue does not block a javascript: href.
const SOURCE_URL_PREFIX = 'https://www.sec.gov/'

const INDICATOR_LABELS: Record<string, string> = {
  fiscal_year_end: 'Fiscal year end',
  revenue_growth_pct: 'Revenue growth (%)',
  net_margin_pct: 'Net margin (%)',
  equity_ratio_pct: 'Equity ratio (%)',
}

const { state, data: summary, error, reload } = useRequest(() => getSummary(props.coverageId))

const isCollecting = ref(false)
const isGenerating = ref(false)
const collectResult = ref<string | null>(null)
const actionError = ref<string | null>(null)

async function collect(): Promise<void> {
  isCollecting.value = true
  collectResult.value = null
  actionError.value = null
  try {
    const report = await collectFinancials(props.coverageId)
    collectResult.value = `Collected ${report.collected} figures.`
  } catch (caught) {
    actionError.value = messageFor(caught, 'Could not collect the financial figures. Please try again.')
  } finally {
    isCollecting.value = false
  }
}

async function generate(): Promise<void> {
  isGenerating.value = true
  actionError.value = null
  try {
    await generateSummary(props.coverageId)
    // Read back through the same request as the first load, so there is one source of page state.
    await reload()
  } catch (caught) {
    actionError.value = messageFor(caught, 'Could not generate the summary. Please try again.')
  } finally {
    isGenerating.value = false
  }
}

function messageFor(caught: unknown, fallback: string): string {
  // Only the API's failures are shown; anything else is a bug and must surface.
  if (!(caught instanceof ApiError)) throw caught
  return SHOWN_AS_IS.has(caught.status) ? caught.message : fallback
}

function labelFor(key: string): string {
  return INDICATOR_LABELS[key] ?? key
}

function isSourceUrl(url: string): boolean {
  return url.startsWith(SOURCE_URL_PREFIX)
}
</script>

<template>
  <section aria-labelledby="summary-heading">
    <h2 id="summary-heading">Plain-language summary</h2>

    <p v-if="state === 'loading'" role="status">Loading summary…</p>

    <template v-else-if="state === 'error'">
      <p v-if="error?.status === NOT_FOUND">No summary has been generated for this coverage yet.</p>
      <div v-else role="alert">
        <p>Could not load the summary.</p>
        <button type="button" class="secondary" @click="reload">Retry</button>
      </div>
    </template>

    <template v-else-if="summary">
      <!-- Model output is untrusted text: interpolated, never v-html. -->
      <p class="summary-text">{{ summary.summary }}</p>
      <p class="field-hint">Generated by {{ summary.model }} at {{ summary.generated_at }}.</p>

      <h3>Figures the summary was written from</h3>
      <dl>
        <template v-for="(value, key) in summary.indicators" :key="key">
          <dt>{{ labelFor(String(key)) }}</dt>
          <dd>{{ value ?? 'Not available' }}</dd>
        </template>
      </dl>

      <h3>Source filings</h3>
      <ul>
        <li v-for="source in summary.sources" :key="`${source.concept}-${source.accn}`">
          <a
            v-if="isSourceUrl(source.url)"
            :href="source.url"
            target="_blank"
            rel="noopener noreferrer"
          >{{ source.form }} filed {{ source.filed }}</a>
          <span v-else>{{ source.form }} filed {{ source.filed }}</span>
          — {{ source.concept }}
        </li>
      </ul>
    </template>

    <!-- One action at a time: a summary generated mid-collection would use half-written figures. -->
    <p>
      <button type="button" class="secondary" :disabled="isCollecting || isGenerating" @click="collect">
        {{ isCollecting ? 'Collecting…' : 'Collect financials' }}
      </button>
      <button type="button" :disabled="isCollecting || isGenerating" @click="generate">
        {{ isGenerating ? 'Generating…' : state === 'success' ? 'Regenerate summary' : 'Generate summary' }}
      </button>
    </p>
    <p v-if="collectResult" role="status">{{ collectResult }}</p>
    <p v-if="actionError" role="alert">{{ actionError }}</p>
  </section>
</template>

<style scoped>
/* Keeps the model's line breaks without rendering any markup. */
.summary-text {
  white-space: pre-line;
}
</style>
